#!/bin/sh
set -eu

fips_root=${FIPS_ELIXIR_ROOT:-/opt/fips-elixir}
ERL_ROOTDIR=${fips_root}/lib/erlang
export ERL_ROOTDIR

"${fips_root}/bin/boring-fips-check" >/dev/null

ERL_AFLAGS="${ERL_AFLAGS:+${ERL_AFLAGS} }-pa ${fips_root}/lib/fips_boot/ebin -crypto fips_mode true -s fips_boot_boringssl verify"
export ERL_AFLAGS

exec "${fips_root}/bin/elixir.real" "$@"
