"""Checksum-locked, architecture-isolated UBI RPM repository imports."""

load("@bazeldnf//bazeldnf:defs.bzl", "rpm")

def _repository_name(prefix, package):
    return "{}_{}".format(prefix, package.replace("+", "p").replace("-", "_"))

def ubi_rpm_labels(prefix, packages):
    """Returns public RpmInfo labels generated by the UBI RPM extension."""
    return ["@{}//rpm".format(_repository_name(prefix, package)) for package in packages]

def _import_lock(module_ctx, tag):
    lock = json.decode(module_ctx.read(tag.lock_file))
    repositories = lock.get("repositories", {})
    locked_packages = {}
    for locked_package in lock.get("rpms", []):
        package = locked_package.get("name", "")
        if not package:
            fail("UBI RPM lock contains an entry without a package name")
        if package in locked_packages:
            fail("UBI RPM lock contains duplicate package '{}'".format(package))
        locked_packages[package] = locked_package

    generated = []
    for package in sorted(tag.packages):
        if package not in locked_packages:
            fail("UBI RPM lock does not contain requested package '{}'".format(package))
        locked_package = locked_packages[package]
        repository = locked_package.get("repository", "")
        base_urls = repositories.get(repository, [])
        relative_urls = locked_package.get("urls", [])
        integrity = locked_package.get("integrity", "")
        if not base_urls or not relative_urls or not integrity:
            fail("UBI RPM '{}' has incomplete repository, URL, or integrity metadata".format(package))

        name = _repository_name(tag.name, package)
        rpm(
            name = name,
            integrity = integrity,
            urls = [
                base.rstrip("/") + "/" + relative.lstrip("/")
                for base in base_urls
                for relative in relative_urls
            ],
        )
        generated.append(name)
    return generated

def _ubi_rpms_impl(module_ctx):
    claimed_names = {}
    root_repositories = []
    for module in module_ctx.modules:
        for tag in module.tags.import_lock:
            if tag.name in claimed_names:
                fail("UBI RPM import name '{}' is declared more than once".format(tag.name))
            claimed_names[tag.name] = True
            generated = _import_lock(module_ctx, tag)
            if module.is_root:
                root_repositories.extend(generated)

    return module_ctx.extension_metadata(
        reproducible = True,
        root_module_direct_deps = root_repositories,
        root_module_direct_dev_deps = [],
    )

_import_lock_tag = tag_class(
    attrs = {
        "name": attr.string(mandatory = True),
        "lock_file": attr.label(
            allow_single_file = [".json"],
            mandatory = True,
        ),
        "packages": attr.string_list(mandatory = True),
    },
)

ubi_rpms = module_extension(
    implementation = _ubi_rpms_impl,
    tag_classes = {"import_lock": _import_lock_tag},
)
